name: stroke-prediction
channels:
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - pandas==2.3.3
      - matplotlib==3.7.2
      - seaborn==0.13.2
      - scikit-learn==1.7.2
      - mlflow==2.19.0
